name: window_rounded_corners
description: "Get Device Window Rounded Corners"
version: 0.0.3
homepage: https://github.com/ongakuer/window_rounded_corners

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.relex.flutter.plugin.window_rounded_corners
        pluginClass: WindowRoundedCornersPlugin